version: '2.3'

x-volumes:
  &default-volumes
    # Define all volumes you would like to have real-time mounted into the docker containers
    volumes:
      - .:/app:delegated ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
      - files:/var/lib/ghost/content

x-environment:
  &default-environment
    # Route that should be used locally, if you are using pygmy, this route *must* end with .docker.amazee.io
    LAGOON_ROUTE: &default-url http://${COMPOSE_PROJECT_NAME:-ghost}.docker.amazee.io
    # Uncomment if you like to have the system behave like in production
    #LAGOON_ENVIRONMENT_TYPE: production

x-user:
  &default-user
    # The default user under which the containers should run. Change this if you are on linux and run with another user than id `1000`
    user: '1000'

volumes:
  files:
    {}

services:

  node:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: node.dockerfile
    labels:
      lagoon.type: node-persistent
      lagoon.persistent.name: node # mount the persistent storage of nginx into this container
      lagoon.persistent: /var/lib/ghost/content/ # location where the persistent storage should be mounted
      lando.type: node-persistent
    volumes:
      - .:/app:delegated
    environment:
      << : *default-environment # loads the defined environment variables from the top
      LAGOON_LOCALDEV_URL: *default-url
      LAGOON_LOCALDEV_HTTP_PORT: 3000
      url: *default-url
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: lagoon
      database__connection__password: lagoon
      database__connection__database: lagoon
      database__pool__min: 0
      database__pool__max: 32
      # mail__transport: ${MAIL_TRANSPORT:-Direct}
      # mail__options__service: ${MAIL_SERVICE}
      # mail__options__host: ${MAIL_HOST}
      # mail__options__port: ${MAIL_PORT:-25}
      # mail__options__secureConnection: ${MAIL_SECURE:-false}
      # mail__options__auth__user: ${MAIL_USER}
      # mail__options__auth__pass: ${MAIL_PASSWORD}
    depends_on:
      - mariadb # basically just tells docker-compose to build the mariadb first

  mariadb:
    image: uselagoon/mariadb:latest
    labels:
      lagoon.type: mariadb
      lando.type: mariadb
    ports:
      - "3306" # exposes the port 3306 with a random local port, find it with `docker-compose port mariadb 3306`
    << : *default-user # uses the defined user from top
    environment:
      << : *default-environment

networks:
  amazeeio-network:
    external: true
